on: [push]
name: LIBCOUTILS CI
jobs:
  build_and_test:
    name: LIBCOUTILS CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Compile tests."
        run: make && make perm

      - name: "Run tests."
        run: ./tester
